const fs = require('fs');
const path = require('path');
const { launchBrowser } = require('../../plugin/puppeteer/useAgent');

// cookie 输出路径（与 cookieResolver 一致）
const COOKIE_PATH = path.resolve(process.cwd(), 'cookies', 'douyin.txt');

function normalizeExpires(expires) {
    // puppeteer cookie.expires is seconds since epoch or undefined
    if (!expires || isNaN(Number(expires))) return 0;
    // ensure integer
    return Math.floor(Number(expires));
}

function sleep(ms) {
    return new Promise((r) => setTimeout(r, ms));
}

async function refreshDouyinCookie() {
    console.log('[douyin] refreshing fresh cookies via puppeteer...');

    const browser = await launchBrowser({
        user_agent:
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
            '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    });

    const page = await browser.newPage();

    await page.setUserAgent(
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
        '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    );

    await page.setViewport({ width: 1366, height: 900 });

    /** 1️⃣ 先打开首页 */
    await page.goto('https://www.douyin.com/', {
        waitUntil: 'domcontentloaded',
        timeout: 30000,
    });

    await sleep(3000);

    /** 2️⃣ 打开一个真实视频页（关键） */
    await page.goto(
        'https://www.douyin.com/video/7581404420148514091',
        { waitUntil: 'domcontentloaded', timeout: 30000 }
    );

    /** 3️⃣ 模拟真实用户行为 */
    await sleep(3000);
    await page.mouse.move(400, 300);
    await sleep(1000);

    /** 滚动页面，触发接口 */
    for (let i = 0; i < 3; i++) {
        await page.mouse.wheel({ deltaY: 800 });
        await sleep(1500);
    }

    /** 4️⃣ 等待抖音 detail 接口返回 */
    try {
        await page.waitForResponse(
            res =>
                res.url().includes('/aweme/v1/web/aweme/detail') &&
                res.status() === 200,
            { timeout: 10000 }
        );
    } catch {
        console.warn('[douyin] detail api not detected, continue anyway');
    }

    const cookies = await page.cookies();
    await browser.close();

    if (!cookies.length) {
        throw new Error('[douyin] failed to obtain cookies');
    }

    /** 写 Netscape cookie */
    const lines = [
        '# Netscape HTTP Cookie File',
        '# Generated by puppeteer for yt-dlp',
        '',
    ];

    for (const c of cookies) {
        lines.push([
            c.domain.startsWith('.') ? c.domain : `.${c.domain}`,
            'TRUE',
            c.path || '/',
            c.secure ? 'TRUE' : 'FALSE',
            normalizeExpires(c.expires),
            c.name,
            c.value,
        ].join('\t'));
    }

    fs.mkdirSync(path.dirname(COOKIE_PATH), { recursive: true });
    fs.writeFileSync(COOKIE_PATH, lines.join('\n'), 'utf8');

    console.log('[douyin] cookie refresh OK');
    return COOKIE_PATH;
}

module.exports = { refreshDouyinCookie };