// tools/douyinCookie.js
const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const COOKIE_DIR = path.resolve(__dirname, '../cookies');
const COOKIE_FILE = path.join(COOKIE_DIR, 'douyin.txt');

function toNetscapeCookie(cookies) {
    const lines = [
        '# Netscape HTTP Cookie File',
        '# Generated by puppeteer',
        ''
    ];

    for (const c of cookies) {
        const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
        const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const secure = c.secure ? 'TRUE' : 'FALSE';
        const expiry = c.expires > 0 ? Math.floor(c.expires) : 1893456000;

        lines.push([
            domain,
            flag,
            c.path || '/',
            secure,
            expiry,
            c.name,
            c.value
        ].join('\t'));
    }

    return lines.join('\n');
}

function waitEnter() {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    return new Promise(resolve => {
        rl.question('\n✅ 已扫码并确认登录后，按回车导出 Cookie...\n', () => {
            rl.close();
            resolve();
        });
    });
}

(async () => {
    if (!fs.existsSync(COOKIE_DIR)) {
        fs.mkdirSync(COOKIE_DIR, { recursive: true });
    }

    const browser = await puppeteer.launch({
        headless: false,
        defaultViewport: null,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
        ],
    });

    const page = await browser.newPage();

    // ⭐ 强烈建议加 UA
    await page.setUserAgent(
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/122 Safari/537.36'
    );

    console.log('👉 正在打开抖音，请扫码登录...');

    await page.goto('https://www.douyin.com', {
        waitUntil: 'domcontentloaded',
        timeout: 0, // ⭐ 关键：禁止超时
    });

    // 人工确认（最稳）
    await waitEnter();

    const cookies = await page.cookies();
    const netscape = toNetscapeCookie(cookies);

    fs.writeFileSync(COOKIE_FILE, netscape, 'utf8');

    console.log('\n🍪 Cookie 已成功保存：');
    console.log(COOKIE_FILE);

    await browser.close();
})();
